payload:
  - PROCESS-NAME,WeChat
  - PROCESS-NAME,QQ
  - PROCESS-NAME,QQMusic
  - PROCESS-NAME,wpsoffice
  - PROCESS-NAME,wpscloudsvr
  - PROCESS-NAME,BaiduNetdisk_mac
  - PROCESS-NAME,aDrive
  - PROCESS-NAME,aDrive Helper
  - DOMAIN-KEYWORD,thetvdb
  - DOMAIN-KEYWORD,themoviedb
